#!/usr/bin/env bash

# Testar se arquivo já existe


# Testar se usuário passou o nome do novo script
[[ $# -ne 1 ]] && echo 'Typ   e a valid filename, please' && exit 1 

# Testar se usuário passou o numero certo de argumentos

echo '#!/usr/bin/env bash' > $1

chmod +x $1

nano $1
